version: 2

builds:
  - id: taskflow
    main: .
    binary: taskflow
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/chenquan/taskflow/cmd.Version={{ .Version }}

archives:
  - formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]

snapshot:
  name_template: "{{ incpatch .Version }}-next"

checksum:
  name_template: checksums.txt

changelog:
  disable: true

# 开启发布功能（默认即为 false，这里显式声明以确保生效）
release:
  disable: false